org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
loom.platform=forge
minecraft_version=1.20.1
forge_version=47.4.22
mod_id=village_pokecenter_guarantee
mod_name=Village PokeCenter Guarantee
mod_version=1.0.0
maven_group=dev.acuario22.villagepokecenter
archives_name=Village-PokeCenter-Guarantee-1.20.1
