org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
loom.platform=forge
minecraft_version=1.20.1
forge_version=47.4.22
cobblemon_version=1.5.2+1.20.1
mod_id=cobblemon_tan_realism
mod_name=Cobblemon TAN Realism
mod_version=1.0.0
maven_group=dev.acuario22.tanrealism
archives_name=Cobblemon-TAN-Realism-1.20.1
