org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
forge_version=47.4.22
cobblemon_version=1.5.2+1.20.1
mod_id=cobblemon_progression_bridge
mod_name=Cobblemon Progression Bridge
mod_version=1.0.0
maven_group=dev.acuario22.cprog
archives_name=Cobblemon-Progression-Bridge-1.20.1
