modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="cobblemon_progression_bridge"
version="${version}"
displayName="Cobblemon Progression Bridge"
authors="Luis / ChatGPT"
description='''Bridge de progresión para Cobblemon 1.5.2 en Forge 1.20.1.'''
[[dependencies.cobblemon_progression_bridge]]
modId="forge"
mandatory=true
versionRange="[47.4.22,)"
ordering="NONE"
side="BOTH"
[[dependencies.cobblemon_progression_bridge]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.cobblemon_progression_bridge]]
modId="cobblemon"
mandatory=true
versionRange="[1.5.2,1.6)"
ordering="AFTER"
side="BOTH"
